// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgency.InfraStructure.Persistence;

#nullable disable

namespace TravelAgency.InfraStructure.Migrations
{
    [DbContext(typeof(TravelAgencyContext))]
    [Migration("20260725220101_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelAgency.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfTravelers")
                        .HasColumnType("int");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Egyptian Pound",
                            Sign = "EGP"
                        },
                        new
                        {
                            Id = 2,
                            Name = "USD",
                            Sign = "$"
                        });
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NameEng")
                        .IsUnique();

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Discover the world's greatest open-air museum with Karnak Temple, Luxor Temple, the Valley of the Kings, and unforgettable Nile cruises.",
                            IsActive = true,
                            NameAr = "الأقصر",
                            NameEng = "Luxor"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Enjoy the beauty of the Nile, Philae Temple, Nubian villages, and the peaceful atmosphere of southern Egypt.",
                            IsActive = true,
                            NameAr = "أسوان",
                            NameEng = "Aswan"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Experience crystal-clear waters, colorful coral reefs, luxury resorts, and exciting water sports on the Red Sea.",
                            IsActive = true,
                            NameAr = "الغردقة",
                            NameEng = "Hurghada"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A world-famous Red Sea destination offering diving, snorkeling, luxury resorts, and vibrant nightlife.",
                            IsActive = true,
                            NameAr = "شرم الشيخ",
                            NameEng = "Sharm El Sheikh"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Visit the Pyramids of Giza, the Egyptian Museum, Khan El Khalili Bazaar, and the historic streets of Old Cairo.",
                            IsActive = true,
                            NameAr = "القاهرة",
                            NameEng = "Cairo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Explore the Mediterranean coastline, Bibliotheca Alexandrina, Citadel of Qaitbay, and rich Greco-Roman history.",
                            IsActive = true,
                            NameAr = "الإسكندرية",
                            NameEng = "Alexandria"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Relax in natural springs, explore the Great Sand Sea, ancient temples, and unique Berber culture.",
                            IsActive = true,
                            NameAr = "واحة سيوة",
                            NameEng = "Siwa Oasis"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A paradise for divers and adventurers, famous for the Blue Hole, desert safaris, and laid-back atmosphere.",
                            IsActive = true,
                            NameAr = "دهب",
                            NameEng = "Dahab"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Discover pristine beaches, diving with dolphins, sea turtles, and untouched coral reefs.",
                            IsActive = true,
                            NameAr = "مرسى علم",
                            NameEng = "Marsa Alam"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Visit the magnificent temples of Ramses II, one of Egypt's most iconic archaeological treasures.",
                            IsActive = true,
                            NameAr = "أبو سمبل",
                            NameEng = "Abu Simbel"
                        });
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.DestinationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1572252009286-268acec5ca0a"
                        },
                        new
                        {
                            Id = 2,
                            DestinationId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1568322445389-f64ac2515020"
                        },
                        new
                        {
                            Id = 3,
                            DestinationId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1591608971362-f08b2a75731a"
                        },
                        new
                        {
                            Id = 4,
                            DestinationId = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1544551763-46a013bb70d5"
                        },
                        new
                        {
                            Id = 5,
                            DestinationId = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e"
                        },
                        new
                        {
                            Id = 6,
                            DestinationId = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1519046904884-53103b34b206"
                        },
                        new
                        {
                            Id = 7,
                            DestinationId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1500375592092-40eb2168fd21"
                        },
                        new
                        {
                            Id = 8,
                            DestinationId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1506744038136-46273834b3fb"
                        },
                        new
                        {
                            Id = 9,
                            DestinationId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda"
                        },
                        new
                        {
                            Id = 10,
                            DestinationId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1572252009286-268acec5ca0a"
                        },
                        new
                        {
                            Id = 11,
                            DestinationId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1539650116574-75c0c6d73f4b"
                        },
                        new
                        {
                            Id = 12,
                            DestinationId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1591608971362-f08b2a75731a"
                        });
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChildNode")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentItineraryId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ParentItineraryId")
                        .IsUnique()
                        .HasFilter("[ParentItineraryId] IS NOT NULL");

                    b.HasIndex("TourId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Logger.Logg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Loggs");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeCancelation")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerChild")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.PackageDestination", b =>
                {
                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("DestinationId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageDestination");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("Durationhours")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeCancel")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeCancelation")
                        .HasColumnType("bit");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerChild")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeatsBooked")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.TourHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourHighlights");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.TourImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourImages");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.TourInclude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourIncludes");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "admin",
                            IsActivated = false,
                            IsAdmin = true,
                            LastName = "admin",
                            Mobile = "01010660737",
                            Nationality = "",
                            Password_Hashed = "WQzhk3zhSwJ6I0HCH2eWAMpmQnXd0qgXtrAMTr+Sbck=",
                            SaltKey = "FN55EN083FYpdN/tdFcLDQ=="
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Customer@gmail.com",
                            FirstName = "Customer",
                            IsActivated = false,
                            IsAdmin = false,
                            LastName = "Customer",
                            Mobile = "01010660747",
                            Nationality = "",
                            Password_Hashed = "WQzhk3zhSwJ6I0HCH2eWAMpmQnXd0qgXtrAMTr+Sbck=",
                            SaltKey = "FN55EN083FYpdN/tdFcLDQ=="
                        });
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Package", "Package")
                        .WithMany("Bookings")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TravelAgency.Domain.Entities.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TravelAgency.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.DestinationImage", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Destination", "Destination")
                        .WithMany("Images")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Itinerary", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Package", "Package")
                        .WithMany("Itinerary")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TravelAgency.Domain.Entities.Itinerary", "ParentItinerary")
                        .WithOne()
                        .HasForeignKey("TravelAgency.Domain.Entities.Itinerary", "ParentItineraryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TravelAgency.Domain.Entities.Tour", "Tour")
                        .WithMany("Itinerary")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Package");

                    b.Navigation("ParentItinerary");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.PackageDestination", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Destination", "Destination")
                        .WithMany("PackageDestination")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TravelAgency.Domain.Entities.Package", "Package")
                        .WithMany("PackageDestination")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Review", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Tour", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.Domain.Entities.Destination", "Destination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.TourHighlight", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Tour", "Tour")
                        .WithMany("Highlights")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.TourImage", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Tour", "Tour")
                        .WithMany("Images")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.TourInclude", b =>
                {
                    b.HasOne("TravelAgency.Domain.Entities.Tour", "Tour")
                        .WithMany("Includes")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PackageDestination");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Package", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Itinerary");

                    b.Navigation("PackageDestination");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Highlights");

                    b.Navigation("Images");

                    b.Navigation("Includes");

                    b.Navigation("Itinerary");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TravelAgency.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
