import { Component, ChangeDetectionStrategy } from '@angular/core';
import { datas } from '../../../../data/data';
import * as i0 from "@angular/core";
const _forTrack0 = ($index, $item) => $item.id;
function TermsOne_For_77_Template(rf, ctx) { if (rf & 1) {
    const _r1 = i0.ɵɵgetCurrentView();
    i0.ɵɵdomElementStart(0, "div", 16)(1, "h2", 20)(2, "button", 21);
    i0.ɵɵdomListener("click", function TermsOne_For_77_Template_button_click_2_listener() { const item_r2 = i0.ɵɵrestoreView(_r1).$implicit; const ctx_r2 = i0.ɵɵnextContext(); return i0.ɵɵresetView(ctx_r2.handleclick(item_r2.id)); });
    i0.ɵɵdomElementStart(3, "span");
    i0.ɵɵtext(4);
    i0.ɵɵdomElementEnd();
    i0.ɵɵnamespaceSVG();
    i0.ɵɵdomElementStart(5, "svg", 22);
    i0.ɵɵdomElement(6, "path", 23);
    i0.ɵɵdomElementEnd()()();
    i0.ɵɵnamespaceHTML();
    i0.ɵɵdomElementStart(7, "div")(8, "div", 24)(9, "p", 25);
    i0.ɵɵtext(10);
    i0.ɵɵdomElementEnd()()()();
} if (rf & 2) {
    const item_r2 = ctx.$implicit;
    const ctx_r2 = i0.ɵɵnextContext();
    i0.ɵɵadvance(2);
    i0.ɵɵclassProp("bg-gray-50", item_r2.id === ctx_r2.activeIndex)("", item_r2.id === ctx_r2.activeIndex)("text-primary", item_r2.id === ctx_r2.activeIndex);
    i0.ɵɵadvance(2);
    i0.ɵɵtextInterpolate(item_r2.title);
    i0.ɵɵadvance();
    i0.ɵɵclassProp("rotate-180", item_r2.id === ctx_r2.activeIndex);
    i0.ɵɵadvance(2);
    i0.ɵɵclassProp("hidden", item_r2.id !== ctx_r2.activeIndex);
    i0.ɵɵadvance(3);
    i0.ɵɵtextInterpolate(item_r2.desc);
} }
export class TermsOne {
    datas = datas;
    activeIndex = 1;
    handleclick(id) {
        this.activeIndex = id;
    }
    static ɵfac = function TermsOne_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || TermsOne)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: TermsOne, selectors: [["app-terms-one"]], decls: 83, vars: 0, consts: [[1, "relative", "md:py-24", "py-16"], [1, "container", "relative"], [1, "md:flex", "justify-center"], [1, "md:w-3/4"], [1, "p-6", "bg-white", "shadow", "dark:shadow-gray-800", "rounded-md"], [1, "text-xl", "font-semibold", "mb-4"], [1, "text-slate-400"], [1, "text-xl", "font-semibold", "mb-4", "mt-8"], [1, "text-primary-600"], [1, "text-slate-400", "mt-3"], [1, "list-none", "text-slate-400", "mt-3"], [1, "flex", "mt-2"], [1, "mdi", "mdi-chevron-right", "text-primary", "text-lg", "align-middle", "me-2"], [1, "flex", "mt-2", "ms-0"], [1, "text-xl", "font-semibold", "mt-8"], ["id", "accordion-collapsefour", "data-accordion", "collapse", 1, "mt-6"], [1, "relative", "shadow", "dark:shadow-gray-800", "rounded-md", "overflow-hidden", "mt-4"], [1, "mt-6"], ["href", "javascript:void(0)", 1, "py-2", "px-5", "inline-block", "font-semibold", "tracking-wide", "border", "align-middle", "duration-500", "text-base", "text-center", "bg-primary", "hover:bg-primary-600", "border-primary", "hover:border-primary-600", "text-white", "rounded-md"], ["href", "javascript:void(0)", 1, "py-2", "px-5", "inline-block", "font-semibold", "tracking-wide", "border", "align-middle", "duration-500", "text-base", "text-center", "bg-transparent", "hover:bg-primary", "border-primary", "text-primary", "hover:text-white", "rounded-md", "ms-2"], [1, "text-base", "font-semibold"], ["type", "button", 1, "flex", "justify-between", "items-center", "p-5", "w-full", "font-medium", "text-start", 3, "click"], ["data-accordion-icon", "", "fill", "currentColor", "viewBox", "0 0 20 20", "xmlns", "http://www.w3.org/2000/svg", 1, "size-4", "shrink-0"], ["fill-rule", "evenodd", "d", "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z", "clip-rule", "evenodd"], [1, "p-5"], [1, "text-slate-400", "dark:text-gray-400"]], template: function TermsOne_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵdomElementStart(0, "section", 0)(1, "div", 1)(2, "div", 2)(3, "div", 3)(4, "div", 4)(5, "h5", 5);
            i0.ɵɵtext(6, "Introduction :");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(7, "p", 6);
            i0.ɵɵtext(8, "It seems that only fragments of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(9, "h5", 7);
            i0.ɵɵtext(10, "User Agreements :");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(11, "p", 6);
            i0.ɵɵtext(12, "The most well-known dummy text is the 'Lorem Ipsum', which is said to have ");
            i0.ɵɵdomElementStart(13, "b", 8);
            i0.ɵɵtext(14, "originated");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(15, " in the 16th century. Lorem Ipsum is ");
            i0.ɵɵdomElementStart(16, "b", 8);
            i0.ɵɵtext(17, "composed");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(18, " in a pseudo-Latin language which more or less ");
            i0.ɵɵdomElementStart(19, "b", 8);
            i0.ɵɵtext(20, "corresponds");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(21, " to 'proper' Latin. It contains a series of real Latin words. This ancient dummy text is also ");
            i0.ɵɵdomElementStart(22, "b", 8);
            i0.ɵɵtext(23, "incomprehensible");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(24, ", but it imitates the rhythm of most European languages in Latin script. The ");
            i0.ɵɵdomElementStart(25, "b", 8);
            i0.ɵɵtext(26, "advantage");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(27, " of its Latin origin and the relative ");
            i0.ɵɵdomElementStart(28, "b", 8);
            i0.ɵɵtext(29, "meaninglessness");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(30, " of Lorum Ipsum is that the text does not attract attention to itself or distract the viewer's ");
            i0.ɵɵdomElementStart(31, "b", 8);
            i0.ɵɵtext(32, "attention");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(33, " from the layout.");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(34, "p", 9);
            i0.ɵɵtext(35, "There is now an ");
            i0.ɵɵdomElementStart(36, "b", 8);
            i0.ɵɵtext(37, "abundance");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(38, " of readable dummy texts. These are usually used when a text is ");
            i0.ɵɵdomElementStart(39, "b", 8);
            i0.ɵɵtext(40, "required purely");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(41, " to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or ");
            i0.ɵɵdomElementStart(42, "b", 8);
            i0.ɵɵtext(43, "nonsensical");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(44, " stories.");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(45, "p", 9);
            i0.ɵɵtext(46, "It seems that only ");
            i0.ɵɵdomElementStart(47, "b", 8);
            i0.ɵɵtext(48, "fragments");
            i0.ɵɵdomElementEnd();
            i0.ɵɵtext(49, " of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(50, "h5", 7);
            i0.ɵɵtext(51, "Restrictions :");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(52, "p", 6);
            i0.ɵɵtext(53, "You are specifically restricted from all of the following :");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(54, "ul", 10)(55, "li", 11);
            i0.ɵɵdomElement(56, "i", 12);
            i0.ɵɵtext(57, "Digital Marketing Solutions for Tomorrow");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(58, "li", 13);
            i0.ɵɵdomElement(59, "i", 12);
            i0.ɵɵtext(60, "Our Talented & Experienced Marketing Agency");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(61, "li", 13);
            i0.ɵɵdomElement(62, "i", 12);
            i0.ɵɵtext(63, "Create your own skin to match your brand");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(64, "li", 13);
            i0.ɵɵdomElement(65, "i", 12);
            i0.ɵɵtext(66, "Digital Marketing Solutions for Tomorrow");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(67, "li", 13);
            i0.ɵɵdomElement(68, "i", 12);
            i0.ɵɵtext(69, "Our Talented & Experienced Marketing Agency");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(70, "li", 13);
            i0.ɵɵdomElement(71, "i", 12);
            i0.ɵɵtext(72, "Create your own skin to match your brand");
            i0.ɵɵdomElementEnd()();
            i0.ɵɵdomElementStart(73, "h5", 14);
            i0.ɵɵtext(74, "Users Question & Answer :");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(75, "div", 15);
            i0.ɵɵrepeaterCreate(76, TermsOne_For_77_Template, 11, 12, "div", 16, _forTrack0);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(78, "div", 17)(79, "a", 18);
            i0.ɵɵtext(80, "Accept");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(81, "a", 19);
            i0.ɵɵtext(82, "Decline");
            i0.ɵɵdomElementEnd()()()()()()();
        } if (rf & 2) {
            i0.ɵɵadvance(76);
            i0.ɵɵrepeater(ctx.datas);
        } }, encapsulation: 2 });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(TermsOne, [{
        type: Component,
        args: [{ selector: 'app-terms-one', changeDetection: ChangeDetectionStrategy.OnPush, template: "<section class=\"relative md:py-24 py-16\">\r\n    <div class=\"container relative\">\r\n        <div class=\"md:flex justify-center\">\r\n            <div class=\"md:w-3/4\">\r\n                <div class=\"p-6 bg-white  shadow dark:shadow-gray-800 rounded-md\">\r\n                    <h5 class=\"text-xl font-semibold mb-4\">Introduction :</h5>\r\n                    <p class=\"text-slate-400\">It seems that only fragments of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>\r\n\r\n                    <h5 class=\"text-xl font-semibold mb-4 mt-8\">User Agreements :</h5>\r\n                    <p class=\"text-slate-400\">The most well-known dummy text is the 'Lorem Ipsum', which is said to have <b class=\"text-primary-600\">originated</b> in the 16th century. Lorem Ipsum is <b class=\"text-primary-600\">composed</b> in a pseudo-Latin language which more or less <b class=\"text-primary-600\">corresponds</b> to 'proper' Latin. It contains a series of real Latin words. This ancient dummy text is also <b class=\"text-primary-600\">incomprehensible</b>, but it imitates the rhythm of most European languages in Latin script. The <b class=\"text-primary-600\">advantage</b> of its Latin origin and the relative <b class=\"text-primary-600\">meaninglessness</b> of Lorum Ipsum is that the text does not attract attention to itself or distract the viewer's <b class=\"text-primary-600\">attention</b> from the layout.</p>\r\n                    <p class=\"text-slate-400 mt-3\">There is now an <b class=\"text-primary-600\">abundance</b> of readable dummy texts. These are usually used when a text is <b class=\"text-primary-600\">required purely</b> to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or <b class=\"text-primary-600\">nonsensical</b> stories.</p>\r\n                    <p class=\"text-slate-400 mt-3\">It seems that only <b class=\"text-primary-600\">fragments</b> of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>\r\n\r\n                    <h5 class=\"text-xl font-semibold mb-4 mt-8\">Restrictions :</h5>\r\n                    <p class=\"text-slate-400\">You are specifically restricted from all of the following :</p>\r\n                    <ul class=\"list-none text-slate-400 mt-3\">\r\n                        <li class=\"flex mt-2\"><i class=\"mdi mdi-chevron-right text-primary text-lg align-middle me-2\"></i>Digital Marketing Solutions for Tomorrow</li>\r\n                        <li class=\"flex mt-2 ms-0\"><i class=\"mdi mdi-chevron-right text-primary text-lg align-middle me-2\"></i>Our Talented & Experienced Marketing Agency</li>\r\n                        <li class=\"flex mt-2 ms-0\"><i class=\"mdi mdi-chevron-right text-primary text-lg align-middle me-2\"></i>Create your own skin to match your brand</li>\r\n                        <li class=\"flex mt-2 ms-0\"><i class=\"mdi mdi-chevron-right text-primary text-lg align-middle me-2\"></i>Digital Marketing Solutions for Tomorrow</li>\r\n                        <li class=\"flex mt-2 ms-0\"><i class=\"mdi mdi-chevron-right text-primary text-lg align-middle me-2\"></i>Our Talented & Experienced Marketing Agency</li>\r\n                        <li class=\"flex mt-2 ms-0\"><i class=\"mdi mdi-chevron-right text-primary text-lg align-middle me-2\"></i>Create your own skin to match your brand</li>\r\n                    </ul>\r\n\r\n                    <h5 class=\"text-xl font-semibold mt-8\">Users Question & Answer :</h5>\r\n\r\n                    <div id=\"accordion-collapsefour\" data-accordion=\"collapse\" class=\"mt-6\">\r\n                        @for (item of datas; track item.id) {\r\n                            <div class=\"relative shadow dark:shadow-gray-800 rounded-md overflow-hidden mt-4\">\r\n                                <h2 class=\"text-base font-semibold\">\r\n                                    <button type=\"button\" (click)=\"handleclick(item.id)\" [class.bg-gray-50]=\"item.id === activeIndex\" [class.]=\"item.id === activeIndex\" [class.text-primary]=\"item.id === activeIndex\" class=\"flex justify-between items-center p-5 w-full font-medium text-start\">\r\n                                        <span>{{ item.title }}</span>\r\n                                        <svg data-accordion-icon class=\"size-4 shrink-0\" [class.rotate-180]=\"item.id === activeIndex\" fill=\"currentColor\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\">\r\n                                            <path fill-rule=\"evenodd\" d=\"M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z\" clip-rule=\"evenodd\"></path>\r\n                                        </svg>\r\n                                    </button>\r\n                                </h2>\r\n                                <div [class.hidden]=\"item.id !== activeIndex\">\r\n                                    <div class=\"p-5\">\r\n                                        <p class=\"text-slate-400 dark:text-gray-400\">{{ item.desc }}</p>\r\n                                    </div>\r\n                                </div>\r\n                            </div>\r\n                        }\r\n                    </div>\r\n\r\n                    <div class=\"mt-6\">\r\n                        <a href=\"javascript:void(0)\" class=\"py-2 px-5 inline-block font-semibold tracking-wide border align-middle duration-500 text-base text-center bg-primary hover:bg-primary-600 border-primary hover:border-primary-600 text-white rounded-md\">Accept</a>\r\n                        <a href=\"javascript:void(0)\" class=\"py-2 px-5 inline-block font-semibold tracking-wide border align-middle duration-500 text-base text-center bg-transparent hover:bg-primary border-primary text-primary hover:text-white rounded-md ms-2\">Decline</a>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n" }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(TermsOne, { className: "TermsOne", filePath: "app/shared/components/utility/terms-one/terms-one.ts", lineNumber: 9 }); })();
