import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormArray, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { TranslatePipe } from '@ngx-translate/core';
import { catchError, finalize, forkJoin, of } from 'rxjs';
import { ApiService } from '../../../core/services/apiservice.service';

@Component({ selector: 'app-hotel-commercial-policies-page', standalone: true, imports: [ReactiveFormsModule, TranslatePipe], templateUrl: './hotel-commercial-policies-page.html', changeDetection: ChangeDetectionStrategy.OnPush })
export class HotelCommercialPoliciesPage implements OnInit {
  hotels: any[] = []; mealPlans: any[] = []; selectedHotelId = 0; saving = false; message = '';
  readonly mealForm = new FormGroup({ id: new FormControl(0, { nonNullable: true }), code: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(20)] }), nameEng: new FormControl('', { nonNullable: true, validators: [Validators.required] }), nameAr: new FormControl('', { nonNullable: true, validators: [Validators.required] }), iconKey: new FormControl('food-outline', { nonNullable: true }), isActive: new FormControl(true, { nonNullable: true }) });
  readonly policyForm = new FormGroup({ policies: new FormArray<FormGroup>([]) });
  constructor(private readonly api: ApiService, private readonly cdr: ChangeDetectorRef) {}
  get policies(): FormArray<FormGroup> { return this.policyForm.controls.policies; }
  ngOnInit(): void { forkJoin({ hotels: this.api.get('Hotels?page=1&pageSize=500').pipe(catchError(() => of(null))), meals: this.api.get('MealPlans').pipe(catchError(() => of(null))) }).subscribe(result => { this.hotels = this.rows(result.hotels); this.mealPlans = this.rows(result.meals); this.cdr.markForCheck(); }); }
  editMeal(plan: any): void { this.mealForm.reset({ id: Number(plan.id), code: plan.code ?? '', nameEng: plan.nameEng ?? '', nameAr: plan.nameAr ?? '', iconKey: plan.iconKey ?? 'food-outline',  isActive: plan.isActive !== false }); }
  resetMeal(): void { this.mealForm.reset({ id: 0, code: '', nameEng: '', nameAr: '', iconKey: 'food-outline',  isActive: true }); }
  saveMeal(): void { if (this.mealForm.invalid) return; const value = this.mealForm.getRawValue(); const request = value.id ? this.api.put(`MealPlans/${value.id}`, value) : this.api.post('MealPlans', value); request.pipe(catchError(() => of(null))).subscribe((response: any) => { this.message = response?.isSuccess ? 'saved' : response?.message || 'pricingSaveError'; if (response?.isSuccess) { this.resetMeal(); this.api.get('MealPlans').subscribe((list: any) => { this.mealPlans = this.rows(list); this.cdr.markForCheck(); }); } this.cdr.markForCheck(); }); }
  loadPolicies(value: unknown): void { this.selectedHotelId = Number(value) || 0; this.policies.clear(); if (!this.selectedHotelId) return; this.api.get(`HotelChildPolicies/Hotels/${this.selectedHotelId}`).pipe(catchError(() => of(null))).subscribe((response: any) => { this.rows(response).forEach(policy => this.addPolicy(policy)); this.cdr.markForCheck(); }); }
  addPolicy(value: any = {}): void { this.policies.push(new FormGroup({ id: new FormControl(Number(value.id ?? 0), { nonNullable: true }), hotelRoomId: new FormControl<number | null>(value.hotelRoomId ?? null), hotelRoomRatePlanId: new FormControl<number | null>(value.hotelRoomRatePlanId ?? null), minAge: new FormControl(Number(value.minAge ?? 0), { nonNullable: true, validators: [Validators.min(0), Validators.max(17)] }), maxAge: new FormControl(Number(value.maxAge ?? 17), { nonNullable: true, validators: [Validators.min(0), Validators.max(17)] }), chargeType: new FormControl(Number(value.chargeType ?? 1), { nonNullable: true }), amount: new FormControl(Number(value.amount ?? 0), { nonNullable: true, validators: [Validators.min(0)] }), bedType: new FormControl(Number(value.bedType ?? 1), { nonNullable: true }), maximumEligibleChildren: new FormControl<number | null>(value.maximumEligibleChildren ?? null), descriptionEng: new FormControl(value.descriptionEng ?? '', { nonNullable: true }), descriptionAr: new FormControl(value.descriptionAr ?? '', { nonNullable: true }), 

   isActive: new FormControl(value.isActive !== false, { nonNullable: true }) })); }
  removePolicy(index: number): void { this.policies.removeAt(index); }
  savePolicies(): void { if (!this.selectedHotelId || this.policyForm.invalid) { this.policyForm.markAllAsTouched(); return; } this.saving = true; this.api.put(`HotelChildPolicies/Hotels/${this.selectedHotelId}`, { hotelId: this.selectedHotelId, policies: this.policies.getRawValue() }).pipe(catchError(() => of(null)), finalize(() => { this.saving = false; this.cdr.markForCheck(); })).subscribe((response: any) => this.message = response?.isSuccess ? 'saved' : response?.message || 'pricingSaveError'); }
  private rows(response: any): any[] { const data = response?.data ?? response; return Array.isArray(data) ? data : Array.isArray(data?.data) ? data.data : []; }
}
