import { Component, ChangeDetectionStrategy } from '@angular/core';
import { RouterLink } from '@angular/router';
import feather from 'feather-icons';
import { FooterOne } from '../../../../layout/footer-one/footer-one';
import { HomeNavbar } from '../../../../layout/home-navbar/home-navbar';
import * as i0 from "@angular/core";
export class UserInvoice {
    logoDark = 'assets/images/main-logo.png';
    logoLight = 'assets/images/main-logo.png';
    ngAfterViewInit() {
        feather.replace();
    }
    static ɵfac = function UserInvoice_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || UserInvoice)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: UserInvoice, selectors: [["app-user-invoice"]], decls: 146, vars: 2, consts: [[1, "relative", "lg:py-24", "py-16", "bg-slate-50"], [1, "container", "relative"], [1, "md:flex", "justify-center", "mt-24"], [1, "lg:w-4/5", "w-full"], [1, "p-6", "rounded-md", "shadow", "dark:shadow-gray-800", "bg-white"], [1, "border-b", "border-gray-100", "dark:border-gray-700", "pb-6"], [1, "md:flex", "justify-between"], ["alt", "", 1, "logo-height", "block", "dark:hidden", 3, "src"], ["alt", "", 1, "logo-height", "hidden", "dark:block", 3, "src"], [1, "flex", "mt-4"], ["data-feather", "link", 1, "size-4", "me-3", "mt-1"], ["href", "#", "target", "_blank", 1, "text-primary", "font-medium"], [1, "mt-6", "md:mt-0", "md:w-56"], [1, "text-lg", "font-semibold"], [1, "list-none"], [1, "flex", "mt-3"], ["data-feather", "map-pin", 1, "size-4", "me-3", "mt-1"], ["href", "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d39206.002432144705!2d-95.4973981212445!3d29.709510002925988!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640c16de81f3ca5%3A0xf43e0b60ae539ac9!2sGerald+D.+Hines+Waterwall+Park!5e0!3m2!1sen!2sin!4v1566305861440!5m2!1sen!2sin", "data-type", "iframe", 1, "lightbox", "text-slate-400"], [1, "flex", "mt-3", "ms-0"], ["data-feather", "mail", 1, "size-4", "me-3", "mt-1"], ["href", "mailto:Info@seaworldholidays.com", 1, "text-slate-400"], ["data-feather", "phone", 1, "size-4", "me-3", "mt-1"], ["href", "tel:+152534-468-854", 1, "text-slate-400"], [1, "mt-6"], [1, "w-24"], [1, "text-slate-400"], [1, "mt-3", "md:w-56"], [1, "relative", "overflow-x-auto", "shadow", "dark:shadow-gray-800", "rounded-md", "mt-6"], [1, "w-full", "text-start", "text-slate-500"], [1, "text-sm", "uppercase", "bg-slate-50"], ["scope", "col", 1, "text-center", "px-6", "py-3", "w-16"], ["scope", "col", 1, "text-start", "px-6", "py-3"], ["scope", "col", 1, "text-center", "px-6", "py-3", "w-20"], ["scope", "col", 1, "text-center", "px-6", "py-3", "w-28"], ["scope", "col", 1, "text-end", "px-6", "py-3", "w-20"], [1, "bg-white"], [1, "text-center", "px-6", "py-4"], ["scope", "row", 1, "text-start", "px-6", "py-4", "font-medium", "text-gray-900", "whitespace-nowrap"], [1, "text-end", "px-6", "py-4"], [1, "bg-white", "border-t", "border-gray-100", "dark:border-gray-700"], [1, "w-56", "ms-auto", "p-5"], [1, "text-slate-400", "flex", "justify-between"], [1, "text-slate-400", "flex", "justify-between", "mt-2"], [1, "flex", "justify-between", "font-semibold", "mt-2"], [1, "invoice-footer", "border-t", "border-gray-100", "dark:border-gray-700", "pt-6"], [1, "text-slate-400", "text-center", "md:text-start"], [1, "mb-0"], ["href", "tel:+152534-468-854", 1, "text-primary"], [1, "mt-4", "md:mt-0"], [1, "text-slate-400", "text-center", "md:text-end"], ["routerLink", "/terms", "target", "_blank", 1, "text-primary"]], template: function UserInvoice_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵelement(0, "app-home-navbar");
            i0.ɵɵelementStart(1, "section", 0)(2, "div", 1)(3, "div", 2)(4, "div", 3)(5, "div", 4)(6, "div", 5)(7, "div", 6)(8, "div");
            i0.ɵɵelement(9, "img", 7)(10, "img", 8);
            i0.ɵɵelementStart(11, "div", 9);
            i0.ɵɵelement(12, "i", 10);
            i0.ɵɵelementStart(13, "a", 11);
            i0.ɵɵtext(14, "www.Sea World.com");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(15, "div", 12)(16, "h5", 13);
            i0.ɵɵtext(17, "Address:");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(18, "ul", 14)(19, "li", 15);
            i0.ɵɵelement(20, "i", 16);
            i0.ɵɵelementStart(21, "a", 17);
            i0.ɵɵtext(22, "1419 Riverwood Drive,");
            i0.ɵɵelement(23, "br");
            i0.ɵɵtext(24, " Redding, CA 96001");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(25, "li", 18);
            i0.ɵɵelement(26, "i", 19);
            i0.ɵɵelementStart(27, "a", 20);
            i0.ɵɵtext(28, "info@Sea World.com");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(29, "li", 18);
            i0.ɵɵelement(30, "i", 21);
            i0.ɵɵelementStart(31, "a", 22);
            i0.ɵɵtext(32, "(+12) 1546-456-856");
            i0.ɵɵelementEnd()()()()()();
            i0.ɵɵelementStart(33, "div", 6)(34, "div", 23)(35, "h5", 13);
            i0.ɵɵtext(36, "Invoice Details :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(37, "ul", 14)(38, "li", 15)(39, "span", 24);
            i0.ɵɵtext(40, "Invoice No. :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(41, "span", 25);
            i0.ɵɵtext(42, "land45845621");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(43, "li", 18)(44, "span", 24);
            i0.ɵɵtext(45, "Name :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(46, "span", 25);
            i0.ɵɵtext(47, "Calvin Carlo");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(48, "li", 18)(49, "span", 24);
            i0.ɵɵtext(50, "Address :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(51, "span", 25);
            i0.ɵɵtext(52, "1962 Pike Street, ");
            i0.ɵɵelement(53, "br");
            i0.ɵɵtext(54, " Diego, CA 92123");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(55, "li", 18)(56, "span", 24);
            i0.ɵɵtext(57, "Phone :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(58, "span", 25);
            i0.ɵɵtext(59, "(+45) 4584-458-695");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(60, "div", 26)(61, "ul", 14)(62, "li", 15)(63, "span", 24);
            i0.ɵɵtext(64, "Date :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(65, "span", 25);
            i0.ɵɵtext(66, "15th Oct, 2021");
            i0.ɵɵelementEnd()()()()();
            i0.ɵɵelementStart(67, "div", 27)(68, "table", 28)(69, "thead", 29)(70, "tr")(71, "th", 30);
            i0.ɵɵtext(72, "No.");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(73, "th", 31);
            i0.ɵɵtext(74, "Items");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(75, "th", 32);
            i0.ɵɵtext(76, "Qty");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(77, "th", 33);
            i0.ɵɵtext(78, "Rate($)");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(79, "th", 34);
            i0.ɵɵtext(80, "Total($)");
            i0.ɵɵelementEnd()()();
            i0.ɵɵelementStart(81, "tbody")(82, "tr", 35)(83, "td", 36);
            i0.ɵɵtext(84, "1");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(85, "th", 37);
            i0.ɵɵtext(86, "Apple MacBook Pro 17\"");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(87, "td", 36);
            i0.ɵɵtext(88, "1");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(89, "td", 36);
            i0.ɵɵtext(90, "280");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(91, "td", 38);
            i0.ɵɵtext(92, "$ 280");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(93, "tr", 39)(94, "td", 36);
            i0.ɵɵtext(95, "2");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(96, "th", 37);
            i0.ɵɵtext(97, "Microsoft Surface Pro");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(98, "td", 36);
            i0.ɵɵtext(99, "1");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(100, "td", 36);
            i0.ɵɵtext(101, "140");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(102, "td", 38);
            i0.ɵɵtext(103, "$ 140");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(104, "tr", 39)(105, "td", 36);
            i0.ɵɵtext(106, "3");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(107, "th", 37);
            i0.ɵɵtext(108, "Magic Mouse 2");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(109, "td", 36);
            i0.ɵɵtext(110, "2");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(111, "td", 36);
            i0.ɵɵtext(112, "50");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(113, "td", 38);
            i0.ɵɵtext(114, "$ 100");
            i0.ɵɵelementEnd()()()()();
            i0.ɵɵelementStart(115, "div", 40)(116, "ul", 14)(117, "li", 41)(118, "span");
            i0.ɵɵtext(119, "Subtotal :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(120, "span");
            i0.ɵɵtext(121, "$ 520");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(122, "li", 42)(123, "span");
            i0.ɵɵtext(124, "Taxes :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(125, "span");
            i0.ɵɵtext(126, "$ 20");
            i0.ɵɵelementEnd()();
            i0.ɵɵelementStart(127, "li", 43)(128, "span");
            i0.ɵɵtext(129, "Total :");
            i0.ɵɵelementEnd();
            i0.ɵɵelementStart(130, "span");
            i0.ɵɵtext(131, "$ 540");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(132, "div", 44)(133, "div", 6)(134, "div")(135, "div", 45)(136, "h6", 46);
            i0.ɵɵtext(137, "Customer Services : ");
            i0.ɵɵelementStart(138, "a", 47);
            i0.ɵɵtext(139, "(+12) 1546-456-856");
            i0.ɵɵelementEnd()()()();
            i0.ɵɵelementStart(140, "div", 48)(141, "div", 49)(142, "h6", 46)(143, "a", 50);
            i0.ɵɵtext(144, "Terms & Conditions");
            i0.ɵɵelementEnd()()()()()()()()()()();
            i0.ɵɵelement(145, "app-footer-one");
        } if (rf & 2) {
            i0.ɵɵadvance(9);
            i0.ɵɵproperty("src", ctx.logoDark, i0.ɵɵsanitizeUrl);
            i0.ɵɵadvance();
            i0.ɵɵproperty("src", ctx.logoLight, i0.ɵɵsanitizeUrl);
        } }, dependencies: [RouterLink, HomeNavbar, FooterOne], encapsulation: 2 });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(UserInvoice, [{
        type: Component,
        args: [{ selector: 'app-user-invoice', imports: [RouterLink, HomeNavbar, FooterOne], changeDetection: ChangeDetectionStrategy.OnPush, template: "<app-home-navbar />\r\n<section class=\"relative lg:py-24 py-16 bg-slate-50 \">\r\n    <div class=\"container relative\">\r\n        <div class=\"md:flex justify-center mt-24\">\r\n            <div class=\"lg:w-4/5 w-full\">\r\n                <div class=\"p-6 rounded-md shadow dark:shadow-gray-800 bg-white \">\r\n                    <div class=\"border-b border-gray-100 dark:border-gray-700 pb-6\">\r\n                        <div class=\"md:flex justify-between\">\r\n                            <div>\r\n                                <img [src]=\"logoDark\" class=\"logo-height block dark:hidden\" alt=\"\">\r\n                                <img [src]=\"logoLight\" class=\"logo-height hidden dark:block\" alt=\"\">\r\n                                <div class=\"flex mt-4\">\r\n                                    <i data-feather=\"link\" class=\"size-4 me-3 mt-1\"></i>\r\n                                    <a href=\"#\" target=\"_blank\" class=\"text-primary  font-medium\">www.Sea World.com</a>\r\n                                </div>\r\n                            </div>\r\n\r\n                            <div class=\"mt-6 md:mt-0 md:w-56\">\r\n                                <h5 class=\"text-lg font-semibold\">Address:</h5>\r\n\r\n                                <ul class=\"list-none\">\r\n                                    <li class=\"flex mt-3\">\r\n                                        <i data-feather=\"map-pin\" class=\"size-4 me-3 mt-1\"></i>\r\n                                        <a href=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d39206.002432144705!2d-95.4973981212445!3d29.709510002925988!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640c16de81f3ca5%3A0xf43e0b60ae539ac9!2sGerald+D.+Hines+Waterwall+Park!5e0!3m2!1sen!2sin!4v1566305861440!5m2!1sen!2sin\" data-type=\"iframe\" class=\"lightbox text-slate-400\">1419 Riverwood Drive,<br/> Redding, CA 96001</a>\r\n                                    </li>\r\n\r\n                                    <li class=\"flex mt-3 ms-0\">\r\n                                        <i data-feather=\"mail\" class=\"size-4 me-3 mt-1\"></i>\r\n                                        <a href=\"mailto:Info@seaworldholidays.com\" class=\"text-slate-400\">info&#64;Sea World.com</a>\r\n                                    </li>\r\n\r\n                                    <li class=\"flex mt-3 ms-0\">\r\n                                        <i data-feather=\"phone\" class=\"size-4 me-3 mt-1\"></i>\r\n                                        <a href=\"tel:+152534-468-854\" class=\"text-slate-400\">(+12) 1546-456-856</a>\r\n                                    </li>\r\n                                </ul>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n\r\n                    <div class=\"md:flex justify-between\">\r\n                        <div class=\"mt-6\">\r\n                            <h5 class=\"text-lg font-semibold\">Invoice Details :</h5>\r\n\r\n                            <ul class=\"list-none\">\r\n                                <li class=\"flex mt-3\">\r\n                                    <span class=\"w-24\">Invoice No. :</span>\r\n                                    <span class=\"text-slate-400\">land45845621</span>\r\n                                </li>\r\n\r\n                                <li class=\"flex mt-3 ms-0\">\r\n                                    <span class=\"w-24\">Name :</span>\r\n                                    <span class=\"text-slate-400\">Calvin Carlo</span>\r\n                                </li>\r\n\r\n                                <li class=\"flex mt-3 ms-0\">\r\n                                    <span class=\"w-24\">Address :</span>\r\n                                    <span class=\"text-slate-400\">1962 Pike Street, <br/> Diego, CA 92123</span>\r\n                                </li>\r\n\r\n                                <li class=\"flex mt-3 ms-0\">\r\n                                    <span class=\"w-24\">Phone :</span>\r\n                                    <span class=\"text-slate-400\">(+45) 4584-458-695</span>\r\n                                </li>\r\n                            </ul>\r\n                        </div>\r\n\r\n                        <div class=\"mt-3 md:w-56\">\r\n                            <ul class=\"list-none\">\r\n                                <li class=\"flex mt-3\">\r\n                                    <span class=\"w-24\">Date :</span>\r\n                                    <span class=\"text-slate-400\">15th Oct, 2021</span>\r\n                                </li>\r\n                            </ul>\r\n                        </div>\r\n                    </div>\r\n\r\n                    <div class=\"relative overflow-x-auto shadow dark:shadow-gray-800 rounded-md mt-6\">\r\n                        <table class=\"w-full text-start text-slate-500 \">\r\n                            <thead class=\"text-sm uppercase bg-slate-50 \">\r\n                                <tr>\r\n                                    <th scope=\"col\" class=\"text-center px-6 py-3 w-16\">No.</th>\r\n                                    <th scope=\"col\" class=\"text-start px-6 py-3\">Items</th>\r\n                                    <th scope=\"col\" class=\"text-center px-6 py-3 w-20\">Qty</th>\r\n                                    <th scope=\"col\" class=\"text-center px-6 py-3 w-28\">Rate($)</th>\r\n                                    <th scope=\"col\" class=\"text-end px-6 py-3 w-20\">Total($)</th>\r\n                                </tr>\r\n                            </thead>\r\n                            <tbody>\r\n                                <tr class=\"bg-white \">\r\n                                    <td class=\"text-center px-6 py-4\">1</td>\r\n                                    <th scope=\"row\" class=\"text-start px-6 py-4 font-medium text-gray-900  whitespace-nowrap\">Apple MacBook Pro 17\"</th>\r\n                                    <td class=\"text-center px-6 py-4\">1</td>\r\n                                    <td class=\"text-center px-6 py-4\">280</td>\r\n                                    <td class=\"text-end px-6 py-4\">$ 280</td>\r\n                                </tr>\r\n                                <tr class=\"bg-white  border-t border-gray-100 dark:border-gray-700\">\r\n                                    <td class=\"text-center px-6 py-4\">2</td>\r\n                                    <th scope=\"row\" class=\"text-start px-6 py-4 font-medium text-gray-900  whitespace-nowrap\">Microsoft Surface Pro</th>\r\n                                    <td class=\"text-center px-6 py-4\">1</td>\r\n                                    <td class=\"text-center px-6 py-4\">140</td>\r\n                                    <td class=\"text-end px-6 py-4\">$ 140</td>\r\n                                </tr>\r\n                                <tr class=\"bg-white  border-t border-gray-100 dark:border-gray-700\">\r\n                                    <td class=\"text-center px-6 py-4\">3</td>\r\n                                    <th scope=\"row\" class=\"text-start px-6 py-4 font-medium text-gray-900  whitespace-nowrap\">Magic Mouse 2</th>\r\n                                    <td class=\"text-center px-6 py-4\">2</td>\r\n                                    <td class=\"text-center px-6 py-4\">50</td>\r\n                                    <td class=\"text-end px-6 py-4\">$ 100</td>\r\n                                </tr>\r\n                            </tbody>\r\n                        </table>\r\n                    </div>\r\n\r\n                    <div class=\"w-56 ms-auto p-5\">\r\n                        <ul class=\"list-none\">\r\n                            <li class=\"text-slate-400 flex justify-between\">\r\n                                <span>Subtotal :</span>\r\n                                <span>$ 520</span>\r\n                            </li>\r\n                            <li class=\"text-slate-400 flex justify-between mt-2\">\r\n                                <span>Taxes :</span>\r\n                                <span>$ 20</span>\r\n                            </li>\r\n                            <li class=\"flex justify-between font-semibold mt-2\">\r\n                                <span>Total :</span>\r\n                                <span>$ 540</span>\r\n                            </li>\r\n                        </ul>\r\n                    </div>\r\n\r\n                    <div class=\"invoice-footer border-t border-gray-100 dark:border-gray-700 pt-6\">\r\n                        <div class=\"md:flex justify-between\">\r\n                            <div>\r\n                                <div class=\"text-slate-400 text-center md:text-start\">\r\n                                    <h6 class=\"mb-0\">Customer Services : <a href=\"tel:+152534-468-854\" class=\"text-primary\">(+12) 1546-456-856</a></h6>\r\n                                </div>\r\n                            </div>\r\n\r\n                            <div class=\"mt-4 md:mt-0\">\r\n                                <div class=\"text-slate-400 text-center md:text-end\">\r\n                                    <h6 class=\"mb-0\"><a routerLink=\"/terms\" target=\"_blank\" class=\"text-primary\">Terms & Conditions</a></h6>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n<app-footer-one />\r\n\r\n" }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(UserInvoice, { className: "UserInvoice", filePath: "app/features/innerpages/my-account/user-invoice/user-invoice.ts", lineNumber: 14 }); })();
